// <auto-generated />
using System;
using BonfireDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonfireDB.Migrations
{
    [DbContext(typeof(DbBonfire))]
    [Migration("20260522135418_AddSeedlingIsPlantedInBed")]
    partial class AddSeedlingIsPlantedInBed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DisplayHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DisplayWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("GridColumns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridRows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlotId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL");

                    b.Property<string>("SoilType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.ToTable("GardenElements");

                    b.HasDiscriminator<string>("ElementType").HasValue("GardenElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GardenPlans");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenPlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CanvasHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("CanvasWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlotType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<double>("WidthMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GardenPlots");

                    b.HasDiscriminator<string>("PlotType").HasValue("GardenPlot");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.PlantingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GardenElementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlantedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeedlingInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GardenElementId");

                    b.HasIndex("SeedlingInfoId");

                    b.ToTable("PlantingSpots");
                });

            modelBuilder.Entity("BonfireDB.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantCultureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantSortId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantCultureId");

                    b.HasIndex("PlantSortId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("BonfireDB.Entities.PlantCulture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlantsCulture");
                });

            modelBuilder.Entity("BonfireDB.Entities.PlantSort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeOfSeedlings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrowingSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LandingPattern")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxGerminationTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinGerminationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantColor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.ToTable("PlantsSort");
                });

            modelBuilder.Entity("BonfireDB.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("BonfireDB.Entities.Replanting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PotVolume")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReplantingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplantingNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeedlingInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeedlingInfoId");

                    b.ToTable("Replants");
                });

            modelBuilder.Entity("BonfireDB.Entities.Seed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedsInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("SeedsInfoId")
                        .IsUnique();

                    b.ToTable("Seeds");
                });

            modelBuilder.Entity("BonfireDB.Entities.Seedling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlantedInBed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LandingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LunarPhase")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlantPlace")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantedOut")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("SeedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedlingSource")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Seedlings");
                });

            modelBuilder.Entity("BonfireDB.Entities.SeedlingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeathNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GerminationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LandingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LunarPhase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotherPlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuarantineCause")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuarantineNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantineStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantineStopDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuenchingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeedlingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedlingNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedlingSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeedlingId");

                    b.ToTable("SeedlingInfos");
                });

            modelBuilder.Entity("BonfireDB.Entities.SeedsInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountSeeds")
                        .HasColumnType("REAL");

                    b.Property<double?>("AmountSeedsWeight")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CostPack")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposeComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("QuantityPack")
                        .HasColumnType("REAL");

                    b.Property<string>("SeedSource")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightPack")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SeedsInfo");
                });

            modelBuilder.Entity("BonfireDB.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeedlingInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentMethod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeedlingInfoId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.Bed", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenElement");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Bed");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.ColdFrame", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenElement");

                    b.Property<string>("CoverMaterial")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ColdFrame");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.FlowerBed", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenElement");

                    b.Property<string>("Shape")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("FlowerBed");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.OpenGroundArea", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenElement");

                    b.HasDiscriminator().HasValue("OpenGroundArea");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.Garden", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenPlot");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("GardenPlanId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("GardenPlanId");

                    b.HasDiscriminator().HasValue("Garden");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.Greenhouse", b =>
                {
                    b.HasBaseType("BonfireDB.Entities.GardenPlanning.GardenPlot");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DisplayHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DisplayWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentPlotId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rotation")
                        .HasColumnType("REAL");

                    b.Property<string>("StateTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasIndex("ParentPlotId");

                    b.HasDiscriminator().HasValue("Greenhouse");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenElement", b =>
                {
                    b.HasOne("BonfireDB.Entities.GardenPlanning.GardenPlot", "Plot")
                        .WithMany("Elements")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.PlantingSpot", b =>
                {
                    b.HasOne("BonfireDB.Entities.GardenPlanning.GardenElement", "GardenElement")
                        .WithMany("PlantingSpots")
                        .HasForeignKey("GardenElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonfireDB.Entities.SeedlingInfo", "SeedlingInfo")
                        .WithMany()
                        .HasForeignKey("SeedlingInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GardenElement");

                    b.Navigation("SeedlingInfo");
                });

            modelBuilder.Entity("BonfireDB.Entities.Plant", b =>
                {
                    b.HasOne("BonfireDB.Entities.PlantCulture", "PlantCulture")
                        .WithMany("Plants")
                        .HasForeignKey("PlantCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonfireDB.Entities.PlantSort", "PlantSort")
                        .WithMany("Plants")
                        .HasForeignKey("PlantSortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantCulture");

                    b.Navigation("PlantSort");
                });

            modelBuilder.Entity("BonfireDB.Entities.PlantSort", b =>
                {
                    b.HasOne("BonfireDB.Entities.Producer", "Producer")
                        .WithMany("PlantSorts")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("BonfireDB.Entities.Replanting", b =>
                {
                    b.HasOne("BonfireDB.Entities.SeedlingInfo", "SeedlingInfo")
                        .WithMany("Replants")
                        .HasForeignKey("SeedlingInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeedlingInfo");
                });

            modelBuilder.Entity("BonfireDB.Entities.Seed", b =>
                {
                    b.HasOne("BonfireDB.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonfireDB.Entities.SeedsInfo", "SeedsInfo")
                        .WithOne("Seed")
                        .HasForeignKey("BonfireDB.Entities.Seed", "SeedsInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("SeedsInfo");
                });

            modelBuilder.Entity("BonfireDB.Entities.Seedling", b =>
                {
                    b.HasOne("BonfireDB.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("BonfireDB.Entities.SeedlingInfo", b =>
                {
                    b.HasOne("BonfireDB.Entities.Seedling", null)
                        .WithMany("SeedlingInfos")
                        .HasForeignKey("SeedlingId");
                });

            modelBuilder.Entity("BonfireDB.Entities.Treatment", b =>
                {
                    b.HasOne("BonfireDB.Entities.SeedlingInfo", "SeedlingInfo")
                        .WithMany("Treatments")
                        .HasForeignKey("SeedlingInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeedlingInfo");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.Garden", b =>
                {
                    b.HasOne("BonfireDB.Entities.GardenPlanning.GardenPlan", "GardenPlan")
                        .WithMany("Gardens")
                        .HasForeignKey("GardenPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GardenPlan");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.Greenhouse", b =>
                {
                    b.HasOne("BonfireDB.Entities.GardenPlanning.GardenPlot", "ParentPlot")
                        .WithMany("Greenhouses")
                        .HasForeignKey("ParentPlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentPlot");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenElement", b =>
                {
                    b.Navigation("PlantingSpots");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenPlan", b =>
                {
                    b.Navigation("Gardens");
                });

            modelBuilder.Entity("BonfireDB.Entities.GardenPlanning.GardenPlot", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Greenhouses");
                });

            modelBuilder.Entity("BonfireDB.Entities.PlantCulture", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BonfireDB.Entities.PlantSort", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("BonfireDB.Entities.Producer", b =>
                {
                    b.Navigation("PlantSorts");
                });

            modelBuilder.Entity("BonfireDB.Entities.Seedling", b =>
                {
                    b.Navigation("SeedlingInfos");
                });

            modelBuilder.Entity("BonfireDB.Entities.SeedlingInfo", b =>
                {
                    b.Navigation("Replants");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("BonfireDB.Entities.SeedsInfo", b =>
                {
                    b.Navigation("Seed")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
